# Generated by Django 4.1.2 on 2022-10-10 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('amount', models.PositiveIntegerField()),
                ('time', models.PositiveIntegerField()),
                ('burned_calories', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.diet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stretching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('description', models.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WarmUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=64)),
                ('intensity', models.IntegerField(choices=[(1, 'for begginers'), (2, 'for begginers and more advanced ones'), (3, 'for advanced ones')])),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutInPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('hour', models.CharField(blank=True, default='8:00', max_length=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.myplan')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(through='FitnessApp.WorkoutExercises', to='FitnessApp.exercise'),
        ),
        migrations.AddField(
            model_name='workout',
            name='warmup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.warmup'),
        ),
        migrations.CreateModel(
            name='WarmupExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.exercise')),
                ('warmup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.warmup')),
            ],
        ),
        migrations.AddField(
            model_name='warmup',
            name='exercises',
            field=models.ManyToManyField(through='FitnessApp.WarmupExercises', to='FitnessApp.exercise'),
        ),
        migrations.CreateModel(
            name='StretchingInPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('hour', models.CharField(blank=True, default='7:00', max_length=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.myplan')),
                ('stretching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.stretching')),
            ],
        ),
        migrations.CreateModel(
            name='StretchingExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.exercise')),
                ('stretching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.stretching')),
            ],
        ),
        migrations.AddField(
            model_name='stretching',
            name='exercises',
            field=models.ManyToManyField(through='FitnessApp.StretchingExercises', to='FitnessApp.exercise'),
        ),
        migrations.AddField(
            model_name='myplan',
            name='stretching',
            field=models.ManyToManyField(through='FitnessApp.StretchingInPlan', to='FitnessApp.stretching'),
        ),
        migrations.AddField(
            model_name='myplan',
            name='workout',
            field=models.ManyToManyField(through='FitnessApp.WorkoutInPlan', to='FitnessApp.workout'),
        ),
    ]
