# Generated by Django 4.1.2 on 2022-10-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stretching',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stretching',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='warmup',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
