# Generated by Django 4.1.2 on 2022-10-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0002_alter_stretching_description_alter_stretching_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplan',
            name='diet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.diet'),
        ),
        migrations.AlterField(
            model_name='myplan',
            name='stretching',
            field=models.ManyToManyField(blank=True, through='FitnessApp.StretchingInPlan', to='FitnessApp.stretching'),
        ),
        migrations.AlterField(
            model_name='myplan',
            name='workout',
            field=models.ManyToManyField(blank=True, through='FitnessApp.WorkoutInPlan', to='FitnessApp.workout'),
        ),
    ]
