# Generated by Django 4.1.2 on 2022-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0003_alter_myplan_diet_alter_myplan_stretching_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplan',
            name='name',
            field=models.CharField(default='My plan', max_length=64),
        ),
    ]
