# Generated by Django 4.1.2 on 2022-10-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0004_myplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.TextField(max_length=250, unique=True),
        ),
    ]
